
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author -asus-
 */
public class frmMain extends javax.swing.JFrame {
    
    /**0
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeniskelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labeltanggal = new javax.swing.JLabel();
        labeljam = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bPrint = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        bDelt = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        bRefresh = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        laki = new javax.swing.JRadioButton();
        per = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        kelas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        tempat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BIODATA SISWA SMK TELKOM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 450, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The Real Informatic Schools");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 180, 17);

        labeltanggal.setForeground(new java.awt.Color(255, 255, 255));
        labeltanggal.setText("Tanggal");
        jPanel1.add(labeltanggal);
        labeltanggal.setBounds(920, 20, 110, 14);

        labeljam.setForeground(new java.awt.Color(255, 255, 255));
        labeljam.setText("Jam");
        jPanel1.add(labeljam);
        labeljam.setBounds(930, 40, 100, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 1050, 70);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ISIAN DATA SISWA");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 120, 14);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 80, 270, 30);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(null);

        bPrint.setBackground(new java.awt.Color(204, 0, 0));
        bPrint.setForeground(new java.awt.Color(255, 255, 255));
        bPrint.setText("Print");
        bPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintActionPerformed(evt);
            }
        });
        jPanel3.add(bPrint);
        bPrint.setBounds(470, 10, 70, 30);

        bSave.setBackground(new java.awt.Color(204, 0, 0));
        bSave.setForeground(new java.awt.Color(255, 255, 255));
        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        jPanel3.add(bSave);
        bSave.setBounds(20, 10, 57, 30);

        bDelt.setBackground(new java.awt.Color(204, 0, 0));
        bDelt.setForeground(new java.awt.Color(255, 255, 255));
        bDelt.setText("Delete");
        bDelt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeltActionPerformed(evt);
            }
        });
        jPanel3.add(bDelt);
        bDelt.setBounds(100, 10, 70, 30);

        bClear.setBackground(new java.awt.Color(204, 0, 0));
        bClear.setForeground(new java.awt.Color(255, 255, 255));
        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });
        jPanel3.add(bClear);
        bClear.setBounds(190, 10, 70, 30);

        bRefresh.setBackground(new java.awt.Color(204, 0, 0));
        bRefresh.setForeground(new java.awt.Color(255, 255, 255));
        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(bRefresh);
        bRefresh.setBounds(280, 10, 80, 30);

        bEdit.setBackground(new java.awt.Color(204, 0, 0));
        bEdit.setForeground(new java.awt.Color(255, 255, 255));
        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        jPanel3.add(bEdit);
        bEdit.setBounds(380, 10, 70, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(290, 80, 770, 50);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIS");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 10, 30, 14);
        jPanel4.add(nis);
        nis.setBounds(10, 30, 250, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(10, 60, 32, 14);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel4.add(nama);
        nama.setBounds(10, 80, 250, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jenis Kelamin");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 110, 90, 14);

        jeniskelamin.add(laki);
        laki.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        laki.setForeground(new java.awt.Color(255, 255, 255));
        laki.setText("Laki-Laki");
        jPanel4.add(laki);
        laki.setBounds(10, 130, 90, 23);

        jeniskelamin.add(per);
        per.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        per.setForeground(new java.awt.Color(255, 255, 255));
        per.setText("Perempuan");
        jPanel4.add(per);
        per.setBounds(120, 130, 90, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kelas");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(10, 280, 30, 14);
        jPanel4.add(email);
        email.setBounds(10, 360, 250, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 340, 30, 14);
        jPanel4.add(kelas);
        kelas.setBounds(10, 300, 250, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Alamat");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 390, 41, 14);

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 410, 250, 96);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tempat Lahir");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(10, 150, 270, 30);
        jPanel4.add(tempat);
        tempat.setBounds(10, 180, 250, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tanggal Lahir");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 210, 270, 30);
        jPanel4.add(jDateChooser1);
        jDateChooser1.setBounds(10, 240, 250, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 120, 270, 530);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setLayout(null);

        tabel1.setForeground(new java.awt.Color(51, 51, 51));
        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Jenis Kelamin", "Kelas", "Email", "Alamat", "Tempat Lahir", "Tanggal Lahir"
            }
        ));
        tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel1);
        if (tabel1.getColumnModel().getColumnCount() > 0) {
            tabel1.getColumnModel().getColumn(3).setResizable(false);
            tabel1.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 750, 490);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(290, 140, 770, 510);

        setBounds(0, 0, 1081, 697);
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(jDateChooser1.getDate());
        String JK = "";
                if(laki.isSelected()){
         
                    JK = "L";
                }  
                if (per.isSelected()){
                    JK = "P";
                }
        if (nis.getText().equals("") || nama.getText().equals("") || tanggal.equals("") || JK.equals("") || 
                kelas.getText().equals("") || email.getText().equals("") || tempat.getText().equals("") || 
                alamat.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi data ", "Error", 
                    JOptionPane.WARNING_MESSAGE);
        } else {
            
            String SQL = "INSERT INTO t_siswa (NIS,NamaSiswa,TempatLahir,TanggalLahir,JenisKelamin,Kelas,Email,Alamat) " 
                    + "VALUES ('"+nis.getText()+"','"+nama.getText()+"','"+tempat.getText()+"','"+jDateChooser1.getDate()+"','"+JK+"','"
                    +kelas.getText()+"','"+email.getText()
                    +"','"+alamat.getText()+"')";
            int status = KoneksiDB.execute(SQL); 
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
              
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }     
        
    }//GEN-LAST:event_bSaveActionPerformed

    private void bDeltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeltActionPerformed
        // TODO add your handling code here:
        int baris = tabel1.getSelectedRow();
       if (baris != -1){
           String NIS = tabel1.getValueAt(baris, 0).toString();
           String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
           int status = KoneksiDB.execute(SQL);
           if (status==1){
               JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
           } else {
               JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
           }
       } else {
           JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_bDeltActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        nis.setText(""); 
        nama.setText("");
        tempat.setText("");
        jDateChooser1.setDate(null);
        kelas.setText("");
        jeniskelamin.clearSelection();
        email.setText("");
        alamat.setText("");
    }//GEN-LAST:event_bClearActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_bRefreshActionPerformed

    private void bPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer  = new MessageFormat("Page {0,number,integer}   ");
        try {
            tabel1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);     
        } catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_bPrintActionPerformed

    
    private void tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel1MouseClicked
        // TODO add your handling code here:
        int baris = tabel1.getSelectedRow();
        if (baris != -1){
            nis.setText(tabel1.getValueAt(baris, 0).toString());
            nama.setText(tabel1.getValueAt(baris, 1).toString());
            tempat.setText(tabel1.getValueAt(baris, 2).toString());
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try {
                dateFormat = date.parse(tabel1.getValueAt(baris, 3).toString());
            } catch (ParseException ex) {
                
            }
            
            jDateChooser1.setDate(dateFormat);
            
            if("Laki-Laki".equals(tabel1.getValueAt(baris,4).toString())){
                laki.setSelected(true);
            }else {
                per.setSelected(true);
            }
            kelas.setText(tabel1.getValueAt(baris, 5).toString());
            email.setText(tabel1.getValueAt(baris, 6).toString());
            alamat.setText(tabel1.getValueAt(baris, 7).toString());
        }
    }//GEN-LAST:event_tabel1MouseClicked

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        if("".equals(nis.getText()) || "".equals(alamat.getText()) || "".equals(kelas.getText()) || "".equals(nama.getText())  || "".equals(email.getText()) || "".equals(tempat.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String JK = "";
            if(laki.isSelected()){
                JK = "L";
            } else {
                JK = "P";
            }
            String SQL = "UPDATE t_siswa SET "
                    +"NamaSiswa='"+nama.getText()+"',"
                    +"TempatLahir='"+tempat.getText()+"',"
                    +"TanggalLahir='"+jDateChooser1.getDate()+"',"
                    +"JenisKelamin='"+JK+"',"
                    +"Kelas='"+kelas.getText()+"',"
                    +"Email='"+email.getText()+"',"
                    +"Alamat='"+alamat.getText()+"',"
                    +"' WHERE NIS='"+nis.getText()+"'" ;
            int status = KoneksiDB.execute(SQL);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
        setTanggal();
            setJam();
    }//GEN-LAST:event_bEditActionPerformed

    /**0
     * 
     * 
     * 
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDelt;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bPrint;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bSave;
    private javax.swing.JTextField email;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup jeniskelamin;
    private javax.swing.JTextField kelas;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nis;
    private javax.swing.JRadioButton per;
    private javax.swing.JTable tabel1;
    private javax.swing.JTextField tempat;
    // End of variables declaration//GEN-END:variables

    
    private void selectData() {
        String kolom[] = {"NIS","NamaSiswa","TempatLahir","TanggalLahir","JenisKelamin","Kelas","Email","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String NIS = rs.getString(1);
                String NamaSiswa = rs.getString(2);
                String TempatLahir = rs.getString(3);
                String TanggalLahir = rs.getString(4);
                String JenisKelamin = "";
                if("L".equals(rs.getString(5))){
                    JenisKelamin = "Laki-Laki";
                }else {
                    JenisKelamin = "Perempuan";
                }
                String Kelas = rs.getString(6);
                String Email = rs.getString(7);
                String Alamat = rs.getString(8);
                
                String data[] = {NIS,NamaSiswa,TempatLahir,TanggalLahir,JenisKelamin,Kelas,Email,Alamat};
                dtm.addRow(data);
            }
        } catch (SQLException ex){
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabel1.setModel(dtm);
    }
    
    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new 
        java.text.SimpleDateFormat("dd/MM/yyyy");
        labeltanggal.setText(kal.format(skrg));
    }
    
    String nol_jam = "";
    String nol_menit = "";
    String nol_detik = "";
    public void setJam(){
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <=9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                labeljam.setText("Jam "+jam+ ":" + menit +":"+detik);
            }
        };
    new Timer(100, taskPerformer).start();
    
    }
}
    
